### ISSUE TITLE
Engineer item 10: Statements not accurate

### ISSUE THREAD

**Issue by aardrian** [voxmedia/accessibility#28]
In item 10 under Engineers, [Avoid text in pseudo elements](http://accessibility.voxmedia.com/#engineers-10), you make an assertion that "added content [via pseudo-elements] is invisible to assistive technology."

That is not accurate.

The [Simply Accessible article](http://simplyaccessible.com/article/three-pitfalls-text-alternatives/) you reference also does not make that claim. In fact, the article is talking about non-text content added in this way, including icon fonts.

Browsers now (and have for some time) expose CSS generated content to assistive technology. Screen readers, for example, will now read it.

I suggest you adjust the heading to "Avoid Images & Iconography in Pseudo-elements." Then adjust the description to note that images added via CSS generated content offer no method (yet, though [work is being done to address that](https://www.w3.org/TR/css-content-3/#alt)) to provide alternative text. Icons, whether via fonts, SVG, or images, also provide no alternative text when added in this way.

**Comment by allypalanzi** [comment]
Thanks!! We've been meaning to fix this, submitted a PR and it should be merged in today :)
