### ISSUE TITLE
[nice-to-have] Create standalone resources section

### ISSUE THREAD

**Issue by ssktanaka** [voxmedia/accessibility#33]
Marvin's suggestion: Have an additional section that was just dedicated to resources (so in addition to the checklist tool). Might be similar to this but for accessibility articles and classes: http://fredsarmento.me/frontend-tools/

**Comment by robdodson** [comment]
Hi there!

I work on the Chrome team, and along with one of our engineers who specializes in accessibility, we've recently put out a free course on a11y fundamentals. We used the Web AIM checklist as a primary guide for much of our course content. I was wondering if this might be useful to include in your resources section? Also, I noticed each check item has a 'source' area underneath it. I was wondering if in some places it might help to link to the videos?

The course is up at bit.ly/web-a11y

**Comment by mcespo** [comment]
Thank you so so much for providing this. One of our next iterations will be to create a dedicated resources section and I would love to append this into the guidelines as well. In general, linking to areas and sourcing to video explanations would be fantastic, and I know a number of us are very humbled that you would reach out to us to propose the idea.

Seriously boss, you ROCK! 🎸

**Comment by robdodson** [comment]
Cool, let me know if there's anything we can do to help :)
